# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Publish Android"
  lane :puan do |options|
    github_publish_token = options[:GITHUB_PUBLISH_TOKEN]
    gradle(task: "kmmBridgePublish -PGITHUB_PUBLISH_TOKEN=#{github_publish_token} -PGITHUB_REPO=jesusdmedinac/kmm-bridge --no-daemon --stacktrace")
  end

  desc "Publish iOS"
  lane :puio do
    env_properties = get_env_properties()
    github_publish_token = env_properties["GITHUB_PUBLISH_TOKEN"]
    gradle(task: "publishIosArm64PublicationToGitHubPackagesRepository publishIosSimulatorArm64PublicationToGitHubPackagesRepository publishIosX64PublicationToGitHubPackagesRepository -PGITHUB_PUBLISH_TOKEN=#{github_publish_token} -PGITHUB_REPO=jesusdmedinac/kmm-bridge --no-daemon --stacktrace")
  end
end

def get_env_properties()
  return File.open("../env.properties")
    .readlines
    .map(&:chomp) # Discard any newline characters (\n)
    .select { |it| it != ""  } # Filter empty elements
    .select { |it| !it.start_with?("#") } # Filter elements that starts with #
    .map { |it| it.split("=") } # Create array for each element
    .to_h # Convert into hash
end
